# Generated by Django 2.2.1 on 2019-08-08 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listarenta',
            name='added_on',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 8)),
        ),
        migrations.AlterField(
            model_name='listarenta',
            name='deleted_on',
            field=models.DateField(blank=True, default=datetime.date(2019, 8, 18)),
        ),
    ]
